DROP DATABASE IF EXISTS 431_VOLLEYBALL;
CREATE DATABASE IF NOT EXISTS 431_VOLLEYBALL;

USE 431_VOLLEYBALL;

CREATE TABLE HomeTeam (
    teamID INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    teamName VARCHAR(100) NOT NULL,
    numPlayers INT(10) UNSIGNED NOT NULL
);

CREATE TABLE OpponentTeam (
    opponentID INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    teamName VARCHAR(100) NOT NULL,
    schoolName VARCHAR(100) NOT NULL,
    numPlayers INT(10) UNSIGNED NOT NULL
);

CREATE TABLE Player (
    playerID INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    teamID INT(10) UNSIGNED NOT NULL,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    position VARCHAR(50) NOT NULL,

    FOREIGN KEY (teamID) REFERENCES HomeTeam(teamID) ON DELETE CASCADE
);

CREATE TABLE GameStats (
    gameID INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    teamID INT(10) UNSIGNED NOT NULL,
    opponentID INT(10) UNSIGNED NOT NULL,
    date DATE NOT NULL,
    totalTimeMins INT(10) UNSIGNED NOT NULL,
    totalTimeSecs INT(10) UNSIGNED NOT NULL,
    result VARchar(100) NOT NULL,

    FOREIGN KEY (teamID) REFERENCES HomeTeam(teamID) ON DELETE CASCADE,
    FOREIGN KEY (opponentID) REFERENCES OpponentTeam(opponentID) ON DELETE CASCADE
);

CREATE TABLE PlayerStats (
    playerID INT(10) UNSIGNED NOT NULL,
    gameID INT(10) UNSIGNED NOT NULL,
    points INT(20) UNSIGNED NOT NULL,
    assists INT(20) UNSIGNED NOT NULL,
    attackSuccessRate DOUBLE(3, 2) NOT NULL,
    defendSuccessRate DOUBLE(3, 2) NOT NULL,
    settingRate DOUBLE(3, 2) NOT NULL,
    serveRate DOUBLE(3, 2) NOT NULL,

    FOREIGN KEY (playerID) REFERENCES Player(playerID) ON DELETE CASCADE,
    FOREIGN KEY (gameID) REFERENCES GameStats(gameID) ON DELETE CASCADE
);

CREATE TABLE Staff (
    staffID INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    teamID INT(10) UNSIGNED NOT NULL,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    role VARCHAR(30) NOT NULL,

    FOREIGN KEY (teamID) REFERENCES HomeTeam(teamID) ON DELETE CASCADE
);

CREATE TABLE SetStats (
    gameID INT(10) UNSIGNED NOT NULL,
    setNumber INT(10) UNSIGNED NOT NULL,
    setTimeSecs INT(10) UNSIGNED NOT NULL,
    setTimeMins INT(10) UNSIGNED NOT NULL,
    firstScore INT(10) UNSIGNED NOT NULL,
    secondScore INT(10) UNSIGNED NOT NULL,

    FOREIGN KEY (gameID) REFERENCES GameStats(gameID) ON DELETE CASCADE
);
